# for cube_petit
robot_base_frame: base_link

transform_tolerance: 0.5
footprint: [[-0.11, 0.11], [0.11, 0.11], [0.11, -0.11], [-0.11, -0.11]]
robot_radius: 0.22
footprint_padding: 0.01

rgbd_obstacles:
  combination_method: 1
  decay_model: 0
laser_obstaclec:
  combination_method: 1

inflater:
  inflation_radius: 1.0
  cost_scaling_factor: 5.0
  inflate_unknown: true



laser_obstacles:
  enabled: true
  observation_sources: pacecat_scan
  combination_method: 1
  pacecat_scan:
     data_type: LaserScan
     topic: /pacecat/scan_filtered
     marking: true
     clearing: true
     min_obstacle_height: 0.05
     max_obstacle_height: 1.0 #0.6
     expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
     observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
     inf_is_valid: true #default false, for laser scans
     clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
     voxel_filter: true           #default off, apply voxel filter to sensor, recommend on 
  

rgbd_obstacles:
  enabled: true
  voxel_decay: 20     #seconds if linear, e^n if exponential
  decay_model: 0      #0=linear, 1=exponential, -1=persistent
  voxel_size:  0.05   #meters
  track_unknown_space: true   #default space is unknown
  observation_persistence: 0.0  #seconds
  max_obstacle_height: 1.2    #meters
  unknown_threshold: 15     #voxel height,
  mark_threshold: 0      #voxel height
  update_footprint_enabled: true
  combination_method: 1      #1=max, 0=override
  obstacle_range: 2.0    #meters
  origin_z: 0.0    #meters
  publish_voxel_map: true   # default off
  transform_tolerance: 0.2    # seconds
  mapping_mode: false  # default off, saves map not for navigation
  map_save_duration: 60     #default 60s, how often to autosave
  observation_sources: kinect_mark kinect_clear
  kinect_mark:
     data_type: PointCloud2
     topic: camera/sd/points_edge #camera/sd/points_filtered
     marking: true
     clearing: false
     min_obstacle_height: 0.05   #default 0, meters
     max_obstacle_height: 1.5     #defaule 3, meters
     expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
     observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
     inf_is_valid: false          #default false, for laser scans
     clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
     voxel_filter: true           #default off, apply voxel filter to sensor, recommend on 
  kinect_clear:
     data_type: PointCloud2
     topic: camera/sd/points_edge
     data_type: LaserScan
     topic: head_scan
     marking: true
     clearing: false #true
     min_obstacle_height: 0.09
     max_obstacle_height: 1.0 #0.6
     expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
     observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
     inf_is_valid: true #default false, for laser scans
     clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
     voxel_filter: true           #default off, apply voxel filter to sensor, recommend on 
