global_frame: odom

width: 1.0
height: 1.0
resolution: 0.01

rolling_window: true
publish_frequency: 5.0
update_frequency: 5.0

rgbd_obstacles:
  voxel_decay:  10
  combination_method: 1
  decay_model: 0
inflater:
  cost_scaling_factor: 4.0 #5
  inflation_radius: 1.0
plugins:
 - {name: rgbd_obstacles, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
 - {name: laser_obstacles,  type: "costmap_2d::ObstacleLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}
