dynamixel_control:
  serial_interface: /dev/ttyDYNAMIXEL_3.4.2
  loop_frequency: 100
  cycle_time_error_threshold: 0.2 # 0.002
  baudrate: 1000000 # in bauds
  read_timeout: 0.1 # in seconds # 0.005
  scan_timeout: 1.0 # in seconds
  # Cofniguration of the servos
  servos:
    right_wheel_joint:
      # hardware ID of the actuator
      id: 1
      offset: 3.14159265359
      #max-speed: 4.0 # in rad
      command_interface: velocity
      reverse: true
    left_wheel_joint:
      id: 2
      offset: 3.14159265359
      command_interface: velocity

