/map_info:
  test_int: 1
  charging_station_pose: [-0.290, -0.029, 0.000, 0.000, 0.000, -0.040, 0.999]

undock_distance: 0.4 #終わったあと離れる距離
undock_velocity: 0.1 #終わったあと離れる速さ

robot_connector_frame: "connector_link" # コネクタのフレーム名
map_frame: "map" # map

start0_distance: 0.5 #1.2
start1_distance: 0.3 #0.8